version: '3'

services:
  user_service:
    container_name: user-service
    image: docker.pkg.github.com/jibber-jabber/users-service/users-service-dev:latest
    ports:
      - 8080:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: postgres
      DB_HOST: users_postgres_db
      DB_PORT: 5432
      JJ_SECRET: ${JJ_SECRET}
      JJ_EXPIRATION: ${JJ_EXPIRATION}

  user_db:
    container_name: users_postgres_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - pgdata_user:/var/lib/postgresql/data

  post_service:
    container_name: post-service
    image: docker.pkg.github.com/jibber-jabber/posts-service/posts-service-dev:latest
    ports:
      - 8081:8081
    environment:
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: postgres
      DB_HOST: posts_postgres_db
      DB_PORT: 5432
      JJ_SECRET: ${JJ_SECRET}
      JJ_EXPIRATION: ${JJ_EXPIRATION}
      AUTH_HOST: user-service
      AUTH_PORT: 8080

  post_db:
    container_name: posts_postgres_db
    image: postgres:12
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - pgdata_post:/var/lib/postgresql/data

  message_service:
    container_name: message-service
    image: docker.pkg.github.com/jibber-jabber/message-service/message-service-dev:latest
    ports:
      -8082:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: postgres
      DB_HOST: message_postgres_db
      DB_PORT: 5432

  message_db:
    container_name: message_postgres_db
    image: postgres:12
    ports:
    - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - pgdata_message:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: docker.pkg.github.com/jibber-jabber/frontend/frontend-dev:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - user_service
      - post_service

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  pgdata_user:
    external: true
  pgdata_post:
    external: true
  pgdata_message:
    external: true